# Generated by Django 3.2.13 on 2022-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noboro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volno', models.IntegerField()),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=8)),
            ],
        ),
    ]
