# Generated by Django 3.2.13 on 2022-06-12 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchnoboro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoboroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('subtitle', models.CharField(max_length=1024, null=True)),
                ('pageno', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=2048, null=True)),
                ('noboro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchnoboro.noboro')),
            ],
        ),
    ]
