# Generated by Django 3.2.13 on 2022-06-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchnoboro', '0002_noborocontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefcode', models.IntegerField(default=0)),
                ('prefname', models.CharField(max_length=64)),
            ],
        ),
    ]
