# Generated by Django 3.2.13 on 2022-06-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchnoboro', '0003_prefecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('readname', models.CharField(max_length=2048)),
                ('height', models.IntegerField(default=0)),
                ('mapurl', models.URLField(max_length=2048, null=True)),
                ('noborocontent', models.ManyToManyField(to='searchnoboro.NoboroContent')),
                ('prefecture', models.ManyToManyField(to='searchnoboro.Prefecture')),
            ],
        ),
    ]
