# Generated by Django 3.2.13 on 2022-06-23 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchnoboro', '0004_mountain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='mapurl',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='noborocontent',
            field=models.ManyToManyField(blank=True, null=True, to='searchnoboro.NoboroContent'),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='prefecture',
            field=models.ManyToManyField(blank=True, null=True, to='searchnoboro.Prefecture'),
        ),
        migrations.AlterField(
            model_name='noborocontent',
            name='content',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='noborocontent',
            name='noboro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='searchnoboro.noboro'),
        ),
        migrations.AlterField(
            model_name='noborocontent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
